repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.403
    hooks:
      - id: pyright
        args: [--level, error]
        additional_dependencies:
          - click>=8.1.7
          - rich>=13.9.4
          - requests>=2.32.3
          - pydantic>=2.10.3
          - pyyaml>=6.0.2
          - python-dotenv>=1.0.1
          - pendulum>=3.0.0
          - holidays>=0.59
          - pytest>=8.4.1


  # bandit は pyproject.toml で設定、手動実行
  # - repo: https://github.com/pycqa/bandit
  #   rev: 1.8.6
  #   hooks:
  #     - id: bandit
  #       args: [-r, rd_burndown/]
  #       exclude: ^rd_burndown/tests/

  # detect-secrets は手動実行のみ
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.5.0
  #   hooks:
  #     - id: detect-secrets
  #       args: [--baseline, .secrets.baseline]
  #       exclude: ^(\.devcontainer/|tests/fixtures/|\.venv/|\.pytest_cache/|\.ruff_cache/|htmlcov/)

  - repo: local
    hooks:
      - id: lizard-complexity
        name: Lizard complexity check
        entry: uv run lizard
        language: system
        files: '\.py$'
        args: [--CCN, '15', rd_burndown/]
        exclude: ^tests/
      - id: test-coverage
        name: Test coverage check (55% minimum)
        entry: bash
        language: system
        pass_filenames: false
        args: [-c, 'if [ -d "rd_burndown" ] && [ -f "pyproject.toml" ]; then uv run pytest --cov=rd_burndown --cov-report=term-missing --cov-fail-under=55; else echo "✅ テストカバレッジチェック: プロジェクト初期化後に実行されます"; fi']

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: [--fix]
        exclude: ^\.devcontainer/
